/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform
Files: scene.gltf [4.16KB] > scene-transformed.glb [58.92KB] (-1316%)
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useRef } from "react";

// Define the rotation step and interval
const rotationStep = Math.PI / 30; // 22.5 degrees per step
const interval = 100; // Update every 100ms

export function ReactAtom3D() {
	const { nodes, materials } = useGLTF("/3d/react-atom.glb");
	const groupRef = useRef<any>();

	// Track the last update time
	const lastUpdateTime = useRef(Date.now());

	useFrame(() => {
		const now = Date.now();
		if (now - lastUpdateTime.current >= interval) {
			if (groupRef.current) {
				// Update the rotation in discrete steps
				groupRef.current.rotation.y += rotationStep;
				lastUpdateTime.current = now;
			}
		}
	});

	return (
		<group ref={groupRef} dispose={null}>
			<mesh
				// @ts-expect-error
				geometry={nodes["React-Logo_Material002_0"].geometry}
				material={materials["Material.002"]}
				position={[0, 0.079, 0]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={[0.392, 0.392, 0.527]}
			/>
		</group>
	);
}

useGLTF.preload("/3d/react-atom.glb");
